### ISSUE TITLE
crontab not working inside container

### ISSUE THREAD

**Issue by megapearl** [jerheij/docker-spotweb#13]
Hi,

The crontab inside the container looks wrong and is not working:
I'm using your 'latest' master branch.

My docker-compose is:

```
  spotweb:
    image: jerheij/spotweb:latest
    container_name: spotweb
    environment:
      - PUID=1015
      - PGID=101
      - TZ=Europe/Amsterdam
      - SQL=mysql
      - SPOTWEB_CRON_RETRIEVE=*/15 * * * * root /usr/bin/php /var/www/spotweb/retrieve.php
    volumes:
      - /home/dockers/spotweb/dbsettings.inc.php:/var/www/spotweb/dbsettings.inc.php
      - /mnt/storage/Uploads/Watchdir:/watchdir
    ports:
      - 8080:80
    restart: unless-stopped
```

But inside the container it looks like:

```
bash-5.1# cat /etc/crontabs/root 
*/15 * * * * root /usr/bin/php /var/www/spotweb/retrieve.php /usr/bin/php /var/www/spotweb/retrieve.php >/var/log/stdout 2>&1
bash-5.1#
```
Why twice? what's wrong?

Regards,
Donald.
