### ISSUE TITLE
no tcp specified

### ISSUE THREAD

**Issue by ikkeenjij36** [jerheij/docker-spotweb#15]
When trying to run with docker i am geeting this error back
`docker: No port specified: :/tcp<empty>.`
Trying to run it on synology ds3622
Hope you can help,cause really need spotweb for my dutch stuff

**Comment by jerheij** [comment]
I have just tested the deployment of the container with the following docker-compose config and it worked just find. I could create the container with sqlite, configure it and get into the main page:
```
---
version: "2.1"
services:
  spotweb:
    image: jerheij/spotweb:latest
    container_name: spotweb
    restart: always
    ports:
      - "8099:80"
    environment:
      TZ: Europe/Amsterdam
      SQL: sqlite
```

Could you please let me know the exact command you're using to try and run the container?

Thanks!
