### ISSUE TITLE
Spotweb via Nginx Reverse Proxy

### ISSUE THREAD

**Issue by megapearl** [jerheij/docker-spotweb#17]
Hi,

First off all thanks for your docker and time to publish it to dockerhub.

I have bit of a strange problem.

Your docker seems to run fine, all apps like radarr and sonarr are integrating fine with it.
But when browsing from within spotweb itself the Download NZB function is only working for the first time (without filtering or browsing through spotweb).
When clicking the green arrow-down button it redirects in my case  to:

`<a onclick="downloadSabnzbd('722836','https://nzbindex.mydomainhere.com/?page=getnzb&amp;action=push-sabnzbd&amp;messageid=pjyWpuvJ3FEqe6PZAxql5@spot.net&amp;apikey=*redacted*','push-sabnzbd')" class="sab_722836 sabnzbd-button" title="Add NZB to SABnzbd queue (s)"> </a>`

The request got forwarded to SabNZBd and it starts downloading.

But when I filter something on the left panel (or any other click in spotweb) the url changes to:
`<a onclick="downloadSabnzbd('722835','https://nzbindex.mydomainhere.com/?search[tree]=&amp;search[unfiltered]=true/?page=getnzb&amp;action=push-sabnzbd&amp;messageid=edRivMqIOPUYp6PZAEIOG@spot.net&amp;apikey=*redacted*','push-sabnzbd')" class="sab_722835 sabnzbd-button" title="Add NZB to SABnzbd queue (s)"> </a>`

And spotweb gives a error in a box:

![image](https://github.com/jerheij/docker-spotweb/assets/3420660/1c3dd161-131f-4365-87be-e3e3b9bfacd6)

When browsing directly to that url it just redirects me back to spotweb interface and nothing happens.

My Reverse proxy config is like:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name nzbindex.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nzbindex.mydomaininhere.com;
        set $upstream_port 8081;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```
My Docker-Compose:

```
  spotweb:
    image: jerheij/spotweb:latest
    container_name: spotweb
    hostname: spotweb
    environment:
      - PUID=1015
      - PGID=101
      - TZ=Europe/Amsterdam
      - SQL=mysql
      - SSL=enabled
      - SPOTWEB_CRON_RETRIEVE=*/15 * * * *
      - SPOTWEB_CRON_CACHE_CHECK=04 * * * *
    volumes:
      - /home/dockers/spotweb/dbsettings.inc.php:/var/www/spotweb/dbsettings.inc.php
      - /mnt/storage/Uploads/Watchdir:/watchdir
      - /home/dockers/swag/etc/letsencrypt/live/mydomaininhere.com/cert.pem:/etc/ssl/web/spotweb.crt
      - /home/dockers/swag/etc/letsencrypt/live/mydomaininhere.com/privkey.pem:/etc/ssl/web/spotweb.key
      - /home/dockers/swag/etc/letsencrypt/live/mydomaininhere.com/chain.pem:/etc/ssl/web/spotweb.chain.crt
    depends_on:
      - sabnzbd
    ports:
      - 8080:80/tcp
      - 8081:443/tcp
    restart: unless-stopped
```

Could it be that the reverse proxy does not redirect multiple query parameters?
Can you see anything wrong in this configuration?

When using the direct url like https://nzbindex.mydomainhere.com:8081/ everything works as expected.

I already tried changing the reverse proxy like:

`proxy_pass $upstream_proto://$upstream_app:$upstream_port$request_uri?$args;`

But it didn't work also.

Hope you can help me out,

Thanks,

Best Regards,
Donald
